#!/bin/bash

if [ -n "$LOAD_COMPLETION" ] ; then
  shopt -s progcomp

  _cnotes_top() {
    local cur
    if [[ ! $COMP_CWORD -gt 2 ]] ; then
      if [[ $COMP_CWORD == "2" ]] ;
        then COMPREPLY=( $($1 ${COMP_WORDS[1]} ls ${COMP_WORDS[2]}) )
        else COMPREPLY=( $($1 ls ${COMP_WORDS[1]}) )
      fi;
    fi;
  }
  _cnotes() {
    local cur
    if [[ ! $COMP_CWORD -gt 1 ]] ; then
      cur=${COMP_WORDS[COMP_CWORD]}
      COMPREPLY=( $($1 ls $cur) )
    fi;
  }

  complete -o filenames -F _cnotes_top notes
  complete -o filenames -F _cnotes_top vnotes
  complete -o filenames -F _cnotes commands
  complete -o filenames -F _cnotes todo
  complete -o filenames -F _cnotes queries
  complete -o filenames -F _cnotes passwords
  complete -o filenames -F _cnotes timesheet

  return
fi;

if [ -z "$ARGS" ] ;
  then ARGS=( $@ )
fi;

if [ -z "$NOTES_DIR" ] ;
  then NOTES_DIR=~/bin/_notes
fi;

if [ ! -d "$NOTES_DIR" ] ; 
  then mkdir -p $NOTES_DIR
fi;

if [ -z "${ARGS[0]}" ] ;
  then 
    TYPE="notes"
    SUB=""
  else
    if [ "${ARGS[0]}" == "ls" ] 
      then cd $NOTES_DIR; ls ${ARGS[1]}* 2> /dev/null | sed -r 's/\w+\.\w+//g' | sed '/^$/d'  ; exit 0;
    fi;
    TYPE="${ARGS[0]}"
    if [ -z "${ARGS[2]}" ] ;
      then 
        if [ -z "${ARGS[1]}" ] ;
          then SUB=""
          else 
            if [ "${ARGS[1]}" == "ls" ] ; 
              then cd $NOTES_DIR; ls $TYPE.* 2> /dev/null | awk -F '.' '{ print $2 }'; exit 0;
              else SUB=".${ARGS[1]}"
            fi;
        fi;
      else
        if [ "${ARGS[1]}" == "ls" ] ;
           then cd $NOTES_DIR; ls $TYPE.${ARGS[2]}* 2> /dev/null | awk -F '.' '{ print $2 }'; exit 0;
        elif [ "${ARGS[1]}" == "rm" ] ;
          then rm -f $NOTES_DIR/$TYPE.${ARGS[2]}; exit 0;
          else echo "invalid note"; exit 1;
        fi;
    fi;
fi;

vi -n $NOTES_DIR/$TYPE$SUB
