#!/bin/bash

for E in `ls $HOME/tmp/env/* 2> /dev/null | sed -r 's/.*tmp\/env\///g'`
do

  if [ -z "$(eval echo \$ENV_${E}_LOADED)" ] ; then
    export ENV_${E}_LOADED=1
    NO_SHELL=1 source set-$E-env
  fi;

done;

if [ -z "$NO_SHELL" ] ;
  then bash
fi;

