#!/bin/bash

JAVADIR=`(cd $HOME/opt/jdk1.6* 2> /dev/null && pwd) || (cd /opt/jdk1.6* 2> /dev/null && pwd)`

if [ -n "$JAVADIR" ] ;
  then export PATH="$JAVADIR/bin:$PATH"
  else echo "could not find java 6"; exit 1;
fi;

if [ -z "$NO_VERSION" ] ; then
  VER=`javac -version 2>&1 | sed 's/\n//g'`
  echo "$VER at $JAVADIR"
fi;

if [ -z "$NO_SHELL" ] ; 
 then bash
fi;

