#!/bin/bash

if [ -n "$1" ] ; then
  sleep $1
fi;

xmodmap ~/.Xmodmap

# trackpad tap
#xinput set-prop 9 283 1
# trackpad speed
#xinput set-prop 9 303 .5

# kernel next
# trackpad tap
#xinput set-prop 9 300 1
# trackpad speed
#xinput set-prop 9 320 .5

