#!/bin/bash

docker_untagged_images() {
  docker images | tail -n +2 | awk '$1 == "<none>" {print $3}'
}
export -f docker_untagged_images

docker_rm_untagged_images() {
  docker_untagged_images | xargs --no-run-if-empty docker rmi $@
}
export -f docker_rm_untagged_images

docker_exited_containers() {
  docker ps -a --filter "status=exited" --filter "dangling=true" | tail -n +2 |  awk '{print $1}'
}
export -f docker_exited_containers

docker_rm_exited_containers() {
  docker_exited_containers | xargs --no-run-if-empty docker rm $@
}
export -f docker_rm_exited_containers

docker_rmi() {
  GREP=$1
  shift
  docker images | grep "$GREP" | awk '{print $3}' | xargs docker rmi
}
export -f docker_rmi

docker_i() {
  if [[ "$1" == "run" ]] ; then
    shift
    if [[ "$1" == "--pwds" ]] ; then
      shift
      EXTRA="-v `pwd`:`pwd` -w `pwd`"
    fi;
    docker run --rm -i -t $EXTRA "$@"
  else
    docker "$@"
  fi;
}
export -f docker_i

if [ -z "$NO_SHELL" ] ;
 then bash
fi;

